# Generated by Django 5.1.5 on 2025-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the course', max_length=200, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Elective', 'Elective')], default='Compulsory', max_length=20)),
                ('type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Dissertation', 'Dissertation'), ('Project', 'Project'), ('Field Work', 'Field Work')], default='Theory', max_length=20)),
                ('cbcs_category', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Core', 'Core'), ('DSE', 'DSE'), ('GE', 'GE'), ('OE', 'OE'), ('VAC', 'VAC'), ('AEC', 'AEC')], default='Major', max_length=20)),
                ('maximum_credit', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')])),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
                'unique_together': {('name', 'code')},
            },
        ),
    ]
