# Generated by Django 5.1.5 on 2025-01-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
